version: "3.7"

services:
    backend:
        image: trada:latest
        container_name: trada
        env_file:
            - .env
        command: python src/main.py
        restart: always
        ports:
            - "9999:9999"
        logging:
            driver: "json-file"
            options:
                max-size: "200M"
                max-file: "5"
