defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

      [entryPoints.websecure.http.tls]
        certResolver = "leresolver"

    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
          priority = 10

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "bvngoc2000@gmail.com"
  storage= "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"

[http.services]
  [http.services.web.loadBalancer]

    [[http.services.web.loadBalancer.servers]]
      url = "http:118.68.133.236:5000"